"""MCP prompts for ControlDesk measurement and recording workflows.

Prompts registered:
  run_measurement_workflow        — configure raster, add signals, record, export
  add_measurement_bookmark        — annotate a running recording with a named bookmark
  manage_data_loggers             — create, configure, run, and remove data loggers
  configure_measurement_triggers  — create trigger rules with time or signal conditions

Measurement tools used across these prompts:
    Core:        controldesk_measurement_start, controldesk_measurement_stop,
                             controldesk_measurement_manage, controldesk_measurement_query
    Lazy tools:  controldesk_measurement_discover, controldesk_measurement_raster_manage,
                             controldesk_measurement_recording_manage, controldesk_measurement_trigger_manage,
                             controldesk_measurement_data_logger_manage

Layer: MCP Prompt adapter — pure Python; no COM or service calls.
"""

from __future__ import annotations

from controldesk_mcp.server.app import mcp

# ── Prompt — Run Measurement Workflow ─────────────────────────────────────────


@mcp.prompt(
    name="run_measurement_workflow",
    description=(
        "End-to-end workflow for configuring and running a ControlDesk measurement recording: "
        "raster setup, signal configuration, buffer tuning, start, stop, and export. "
        "Accepts optional raster name, sample time, signal list, and recording name."
    ),
)
def run_measurement_workflow(
    raster_name: str = "BaseSampleRaster",
    sample_time_ms: float = 10.0,
    signals: str = "",
    recording_name: str = "",
) -> list[dict]:
    """Generate a measurement recording workflow prompt."""
    signal_step = (
        f"   Add each of these signals: {signals}."
        if signals
        else "   Call `controldesk_measurement_query` with action='list_signals' first to browse signals."
    )
    export_hint = f" with recording_name='{recording_name}'" if recording_name else ""

    return [
        {
            "role": "user",
            "content": (
                f"Configure and run a ControlDesk measurement recording.\n\n"
                f"**Parameters:**\n"
                f"- Raster: `{raster_name}` at {sample_time_ms} ms sample time\n"
                f"- Signals: {signals or '(to be selected)'}\n"
                f"- Recording name: {recording_name or '(auto-generated by ControlDesk)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `controldesk_measurement_query` with action='get_state' — if already running, call "
                f"   `controldesk_measurement_stop` first.\n"
                f"2. Call `controldesk_measurement_query` with action='get_configuration'.\n"
                f"3. Call `controldesk_measurement_discover` to activate raster and recording tools.\n"
                f"4. Call `controldesk_measurement_raster_manage` with action='raster_list'. "
                f"   If `{raster_name}` is missing, use action='raster_add' with "
                f"   raster_interval_ms={sample_time_ms}.\n"
                f"5. {signal_step}\n"
                f"6. Call `controldesk_measurement_manage` to configure signals and settings{export_hint}.\n"
                f"7. Call `controldesk_measurement_start` to begin recording.\n"
                f"8. After the desired duration, call `controldesk_measurement_stop`.\n"
                f"9. Call `controldesk_measurement_recording_manage` with action='list_recordings' to confirm the file.\n"
                f"10. Report: raster used, signals captured, recording path, and duration."
            ),
        }
    ]


# ── Prompt — Add Measurement Bookmark ────────────────────────────────────────


@mcp.prompt(
    name="add_measurement_bookmark",
    description=(
        "Guided workflow for annotating a running measurement recording with a bookmark. "
        "Bookmarks mark key events (e.g., test start, fault injection) in the recording "
        "so they can be identified during post-processing. "
        "Accepts an optional bookmark label."
    ),
)
def add_measurement_bookmark(
    label: str = "",
) -> list[dict]:
    """Generate a measurement bookmark workflow prompt."""
    label_arg = f", title='{label}'" if label else ""

    return [
        {
            "role": "user",
            "content": (
                f"Add a bookmark to the active ControlDesk measurement recording.\n\n"
                f"**Parameters:**\n"
                f"- Label: {label or '(auto-generated)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `controldesk_measurement_query` with action='get_state' to confirm a recording is running. "
                f"   If not running, start one first (see `run_measurement_workflow` prompt).\n"
                f"2. Call `controldesk_measurement_discover` to activate recording tools.\n"
                f"3. Call `controldesk_measurement_recording_manage` with action='bookmark_add'{label_arg} to insert the bookmark "
                f"   at the current timestamp.\n"
                f"4. Use action='bookmark_list' to confirm the bookmark; use action='bookmark_remove' to remove one.\n"
                f"5. Report: bookmark label, timestamp, and total bookmark count."
            ),
        }
    ]


# ── Prompt — Manage Data Loggers ──────────────────────────────────────────────


@mcp.prompt(
    name="manage_data_loggers",
    description=(
        "Guided workflow for creating and managing ControlDesk data loggers: "
        "create a named logger, configure its output file, start/stop logging, "
        "list all loggers, and remove when done. "
        "Data loggers capture signals to external files independently of the main "
        "measurement recording."
    ),
)
def manage_data_loggers(
    logger_name: str = "",
    output_file: str = "",
) -> list[dict]:
    """Generate a data logger management workflow prompt."""
    name_arg = f", name='{logger_name}'" if logger_name else ""
    file_arg = f", output_file_path='{output_file}'" if output_file else ""

    return [
        {
            "role": "user",
            "content": (
                f"Create and run a ControlDesk data logger.\n\n"
                f"**Parameters:**\n"
                f"- Logger name: {logger_name or '(auto-generated)'}\n"
                f"- Output file: {output_file or '(auto-generated)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `controldesk_measurement_discover` to activate data logger tools.\n"
                f"2. Call `controldesk_measurement_data_logger_manage` with action='list' to see existing loggers.\n"
                f"3. Call `controldesk_measurement_data_logger_manage` with action='create'{name_arg}.\n"
                f"4. Call `controldesk_measurement_data_logger_manage` with action='configure'{file_arg}.\n"
                f"5. Call `controldesk_measurement_start` to start the measurement (required before "
                f"   data loggers can record).\n"
                f"6. Use action='start' to begin writing and action='stop' to flush and close the file.\n"
                f"7. When no longer needed, use action='remove'.\n"
                f"8. Report: logger name, output file path, capture duration."
            ),
        }
    ]


# ── Prompt — Configure Measurement Triggers ───────────────────────────────────


@mcp.prompt(
    name="configure_measurement_triggers",
    description=(
        "Guided workflow for configuring ControlDesk measurement triggers: "
        "create trigger rules with time-limit or signal-based conditions "
        "to automatically start or stop recordings. "
        "Accepts optional signal path for trigger-based conditions."
    ),
)
def configure_measurement_triggers(
    signal_path: str = "",
) -> list[dict]:
    """Generate a measurement trigger configuration workflow prompt."""
    signal_hint = f"on signal `{signal_path}`" if signal_path else "on a signal of your choice"

    return [
        {
            "role": "user",
            "content": (
                f"Configure measurement triggers in ControlDesk.\n\n"
                f"**Parameters:**\n"
                f"- Trigger signal: {signal_path or '(to be selected)'}\n\n"
                f"**Trigger types available:**\n\n"
                f"**Time-limit trigger** (stops recording after a fixed duration):\n"
                f"1. Call `controldesk_measurement_discover` to activate trigger tools.\n"
                f"2. Call `controldesk_measurement_trigger_manage` with action='rule_create' to create a rule.\n"
                f"3. Call `controldesk_measurement_trigger_manage` with action='condition_time_limit' to configure the duration "
                f"   (e.g., stop_after_seconds=60).\n\n"
                f"**Signal-based trigger** (starts or stops on a variable threshold):\n"
                f"1. Call `controldesk_measurement_trigger_manage` with action='rule_create' to create a rule.\n"
                f"2. Call `controldesk_measurement_trigger_manage` with action='condition_trigger_based' to configure the condition "
                f"   {signal_hint}: set the signal path, threshold, and direction "
                f"   (rising/falling/either).\n\n"
                f"**Common steps after creating trigger rules:**\n"
                f"3. Call `controldesk_measurement_start` — the trigger will control recording.\n"
                f"4. When done testing, call `controldesk_measurement_trigger_manage` with action='rule_remove' to delete rules no "
                f"   longer needed.\n"
                f"5. Report: trigger rule names, condition types, and configured thresholds."
            ),
        }
    ]
