"""MCP prompts for ControlDesk measurement and recording workflows.

Prompts registered:
  run_measurement_workflow        — configure raster, add signals, record, export
  add_measurement_bookmark        — annotate a running recording with a named bookmark
  manage_data_loggers             — create, configure, run, and remove data loggers
  configure_measurement_triggers  — create trigger rules with time or signal conditions

All 28 measurement-domain tools are covered across these prompts:
  Recording:         measurement_start, measurement_stop, measurement_get_state,
                     measurement_configure_settings, measurement_configure_buffer,
                     measurement_get_configuration
  Signal management: measurement_signal_add, measurement_signal_remove,
                     measurement_list_signals
  Raster management: measurement_raster_add, measurement_raster_list,
                     measurement_raster_remove
  Data export:       measurement_list_recordings, measurement_export_recording,
                     measurement_import_recording
  Bookmarks:         measurement_bookmark_add, measurement_bookmark_list,
                     measurement_bookmark_remove
  Triggers:          trigger_rule_create, trigger_rule_remove,
                     trigger_condition_time_limit, trigger_condition_trigger_based
  Data logging:      data_logger_create, data_logger_configure, data_logger_start,
                     data_logger_stop, data_logger_list, data_logger_remove

Layer: MCP Prompt adapter — pure Python; no COM or service calls.
"""

from __future__ import annotations

from controldesk_mcp.server.app import mcp

# ── Prompt — Run Measurement Workflow ─────────────────────────────────────────


@mcp.prompt(
    name="run_measurement_workflow",
    description=(
        "End-to-end workflow for configuring and running a ControlDesk measurement recording: "
        "raster setup, signal configuration, buffer tuning, start, stop, and export. "
        "Accepts optional raster name, sample time, signal list, and recording name."
    ),
)
def run_measurement_workflow(
    raster_name: str = "BaseSampleRaster",
    sample_time_ms: float = 10.0,
    signals: str = "",
    recording_name: str = "",
) -> list[dict]:
    """Generate a measurement recording workflow prompt."""
    signal_step = (
        f"   Add each of these signals: {signals}."
        if signals
        else "   Call `measurement_list_signals` first to browse available signals, "
        "then add the ones you need with `measurement_signal_add`."
    )
    export_hint = f" with recording_name='{recording_name}'" if recording_name else ""

    return [
        {
            "role": "user",
            "content": (
                f"Configure and run a ControlDesk measurement recording.\n\n"
                f"**Parameters:**\n"
                f"- Raster: `{raster_name}` at {sample_time_ms} ms sample time\n"
                f"- Signals: {signals or '(to be selected)'}\n"
                f"- Recording name: {recording_name or '(auto-generated by ControlDesk)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `measurement_get_state` — if already running, call "
                f"   `measurement_stop` first.\n"
                f"2. Call `measurement_get_configuration` to see current settings.\n"
                f"3. Call `measurement_raster_list` to view existing rasters. "
                f"   If `{raster_name}` is missing, call `measurement_raster_add` with "
                f"   raster_name='{raster_name}', sample_time_ms={sample_time_ms}.\n"
                f"4. {signal_step}\n"
                f"   Use `measurement_signal_add` for each signal. To remove unwanted "
                f"   signals, use `measurement_signal_remove`.\n"
                f"5. Call `measurement_configure_buffer` to set buffer size and overflow "
                f"   behavior if defaults are insufficient.\n"
                f"6. Call `measurement_configure_settings`{export_hint} if a recording "
                f"   name was specified.\n"
                f"7. Call `measurement_start` to begin recording.\n"
                f"8. After the desired duration, call `measurement_stop`.\n"
                f"9. Call `measurement_list_recordings` to confirm the file was saved.\n"
                f"10. Optionally call `measurement_export_recording` to convert to MF4, "
                f"   or `measurement_import_recording` to load an existing recording.\n"
                f"11. To clean up rasters no longer needed: `measurement_raster_remove`.\n"
                f"12. Report: raster used, signals captured, recording path, and duration."
            ),
        }
    ]


# ── Prompt — Add Measurement Bookmark ────────────────────────────────────────


@mcp.prompt(
    name="add_measurement_bookmark",
    description=(
        "Guided workflow for annotating a running measurement recording with a bookmark. "
        "Bookmarks mark key events (e.g., test start, fault injection) in the recording "
        "so they can be identified during post-processing. "
        "Accepts an optional bookmark label."
    ),
)
def add_measurement_bookmark(
    label: str = "",
) -> list[dict]:
    """Generate a measurement bookmark workflow prompt."""
    label_arg = f", label='{label}'" if label else ""

    return [
        {
            "role": "user",
            "content": (
                f"Add a bookmark to the active ControlDesk measurement recording.\n\n"
                f"**Parameters:**\n"
                f"- Label: {label or '(auto-generated)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `measurement_get_state` to confirm a recording is running. "
                f"   If not running, start one first (see `run_measurement_workflow` prompt).\n"
                f"2. Call `measurement_bookmark_add`{label_arg} to insert the bookmark "
                f"   at the current timestamp.\n"
                f"3. Call `measurement_bookmark_list` to confirm the bookmark was recorded.\n"
                f"4. To remove a bookmark by index: call `measurement_bookmark_remove`.\n"
                f"5. Report: bookmark label, timestamp, and total bookmark count."
            ),
        }
    ]


# ── Prompt — Manage Data Loggers ──────────────────────────────────────────────


@mcp.prompt(
    name="manage_data_loggers",
    description=(
        "Guided workflow for creating and managing ControlDesk data loggers: "
        "create a named logger, configure its output file, start/stop logging, "
        "list all loggers, and remove when done. "
        "Data loggers capture signals to external files independently of the main "
        "measurement recording."
    ),
)
def manage_data_loggers(
    logger_name: str = "",
    output_file: str = "",
) -> list[dict]:
    """Generate a data logger management workflow prompt."""
    name_arg = f", name='{logger_name}'" if logger_name else ""
    file_arg = f", output_file='{output_file}'" if output_file else ""

    return [
        {
            "role": "user",
            "content": (
                f"Create and run a ControlDesk data logger.\n\n"
                f"**Parameters:**\n"
                f"- Logger name: {logger_name or '(auto-generated)'}\n"
                f"- Output file: {output_file or '(auto-generated)'}\n\n"
                f"**Steps — execute in order:**\n\n"
                f"1. Call `data_logger_list` to see existing loggers and their states.\n"
                f"2. Call `data_logger_create`{name_arg} to create a new logger.\n"
                f"3. Call `data_logger_configure`{file_arg} to set the output file path, "
                f"   file format, and signals to capture.\n"
                f"4. Call `measurement_start` to start the measurement (required before "
                f"   data loggers can record).\n"
                f"5. Call `data_logger_start` to begin writing data to the output file.\n"
                f"6. When done, call `data_logger_stop` to flush and close the file.\n"
                f"7. Call `data_logger_list` to confirm the logger stopped cleanly.\n"
                f"8. When the logger is no longer needed: call `data_logger_remove`.\n"
                f"9. Report: logger name, output file path, capture duration."
            ),
        }
    ]


# ── Prompt — Configure Measurement Triggers ───────────────────────────────────


@mcp.prompt(
    name="configure_measurement_triggers",
    description=(
        "Guided workflow for configuring ControlDesk measurement triggers: "
        "create trigger rules with time-limit or signal-based conditions "
        "to automatically start or stop recordings. "
        "Accepts optional signal path for trigger-based conditions."
    ),
)
def configure_measurement_triggers(
    signal_path: str = "",
) -> list[dict]:
    """Generate a measurement trigger configuration workflow prompt."""
    signal_hint = f"on signal `{signal_path}`" if signal_path else "on a signal of your choice"

    return [
        {
            "role": "user",
            "content": (
                f"Configure measurement triggers in ControlDesk.\n\n"
                f"**Parameters:**\n"
                f"- Trigger signal: {signal_path or '(to be selected)'}\n\n"
                f"**Trigger types available:**\n\n"
                f"**Time-limit trigger** (stops recording after a fixed duration):\n"
                f"1. Call `trigger_rule_create` to create a named trigger rule.\n"
                f"2. Call `trigger_condition_time_limit` to configure the duration "
                f"   (e.g., stop_after_seconds=60).\n\n"
                f"**Signal-based trigger** (starts or stops on a variable threshold):\n"
                f"1. Call `trigger_rule_create` to create a named trigger rule.\n"
                f"2. Call `trigger_condition_trigger_based` to configure the condition "
                f"   {signal_hint}: set the signal path, threshold, and direction "
                f"   (rising/falling/either).\n\n"
                f"**Common steps after creating trigger rules:**\n"
                f"3. Call `measurement_start` — the trigger will control recording.\n"
                f"4. When done testing, call `trigger_rule_remove` to delete rules no "
                f"   longer needed.\n"
                f"5. Report: trigger rule names, condition types, and configured thresholds."
            ),
        }
    ]
